### ISSUE TITLE
Windows self-path fails on Yggdrasil

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/libblastrampoline#110]
It seems that [Yggdrasil Windows builder](https://github.com/JuliaPackaging/Yggdrasil/pull/6462) does not like #103.
 
```
[13:48:16] libblastrampoline.c: In function ‘DllMain’:
--
  | [13:48:16] libblastrampoline.c:404:1: error: parameter name omitted
  | [13:48:16]  BOOL APIENTRY DllMain(HINSTANCE hModule, DWORD code, void *) {
  | [13:48:16]  ^~~~
  | [13:48:16] make: *** [Makefile:55: build/libblastrampoline.o] Error 1
  | [13:48:16] make: *** Waiting for unfinished jobs....
  | [13:48:19]  ---> make -j${nproc} prefix=${prefix} install
  | [13:48:19]  ---> make -j${nproc} prefix=${prefix} install
  | [13:48:19] Previous command exited with 2
  | [13:48:19] Child Process exited, exit code 2
```

https://buildkite.com/julialang/yggdrasil/builds/1752#01872351-9817-4473-9196-3e177c0f85a1

**Comment by giordano** [comment]
> It seems that https://github.com/JuliaPackaging/Yggdrasil/pull/6462 does not like https://github.com/JuliaLinearAlgebra/libblastrampoline/pull/103.

Sounds like you only have to give a name to the last argument?

> Perhaps we should set up github actions CI on this repo to build PRs on windows, mac and linux.

There's already a CI setup for this package.

**Comment by ViralBShah** [comment]
> > It seems that [JuliaPackaging/Yggdrasil#6462](https://github.com/JuliaPackaging/Yggdrasil/pull/6462) does not like #103.
> 
> Sounds like you only have to give a name to the last argument?

Will try.
 
> There's already a CI setup for this package.

We don't have Windows, I believe.

**Comment by giordano** [comment]
> We don't have Windows, I believe.

This is tested on Windows (but not with MinGW):
https://github.com/JuliaLinearAlgebra/libblastrampoline/blob/918a7cce804d6e9272a659d6cd7431be1ae45545/.buildkite/test_windows.yml#L1-L22

> But also not sure if migrating to github actions is worth the effort, given that this is a slow moving package.

For what is worth, CI on this package was running on GitHub Actions until #92.

**Comment by ViralBShah** [comment]
Oh I see. Whenever I see a bunch of other stuff along with buildkite, I tend to not click through. Thanks and sorry for the noise.
