### ISSUE TITLE
Number of threads with MKL 2023.1

### ISSUE THREAD

**Issue by amontoison** [JuliaLinearAlgebra/libblastrampoline#116]
With the new release of `MKL 2023.1`, the function to set the number of threads is not working anymore.
https://github.com/JuliaLinearAlgebra/MKL.jl/pull/123

**Comment by ViralBShah** [comment]
Also related : #74

**Comment by ViralBShah** [comment]
This worked for me on 64-bit linux. Also, 2023.2 is out.

**Comment by ViralBShah** [comment]
Do we still need to fix something here?
