### ISSUE TITLE
Error: no BLAS/LAPACK library loaded!  -- PROPACK.jl

### ISSUE THREAD

**Issue by amontoison** [JuliaLinearAlgebra/libblastrampoline#117]
I recently compiled PROPACK with LBT and a user was unable to use it MKL.
PROPACK requires an ILP64 BLAS and I don't understand why switching to another backend is not working.
https://github.com/JuliaSmoothOptimizers/PROPACK.jl/issues/54 

```julia
julia> using PROPACK
julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries: 
└ [ILP64] libopenblas64_.so

julia> tsvd(rand(20, 20))

([-0.22500001381615176; -0.22976088455209862; … ; -0.24443800988345776; -0.2390685450952052;;], [10.121123857038096], [-0.19458837206408175; -0.22006568046133926; … ; -0.17804647580393684; -0.22870075370120846;;], [1.1357215518033364e-36], 11, 11)
```
```julia
julia> using PROPACK
julia> using MKL
julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries: 
├ [ILP64] libmkl_rt.so
└ [ LP64] libmkl_rt.so

julia> tsvd(rand(20, 20))
Error: no BLAS/LAPACK library loaded!
([-4.67282983435e-311; 2.37152099006e-311; … ; -9.8452633572525e-311; 1.8422879014037e-310;;], [6.9149587937626e-310], [-0.10445689753014475; 0.2902031860591114; … ; -0.20390069222252044; -0.32014726145774497;;], [0.0], 11, 11)
```

**Comment by amontoison** [comment]
I have exactly the same error with BLIS:
```julia
julia> BLAS.lbt_forward("/home/alexis/.julia/artifacts/6908daa58e00fa4a08ae4cab660690ee5b9d4630/lib/libblis.so", clear=true, verbose=true)
Generating forwards to /home/alexis/.julia/artifacts/6908daa58e00fa4a08ae4cab660690ee5b9d4630/lib/libblis.so
 -> Autodetected symbol suffix "64_"
 -> Autodetected interface ILP64 (64-bit)
 -> Autodetected normal complex return style
 -> Autodetected gfortran calling convention
 -> CBLAS not found
Processed 4945 symbols; forwarded 157 symbols with 64-bit interface and mangling to a suffix of "64_"
157

julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries: 
└ [ILP64] libblis.so

julia> tsvd(rand(20, 20))
Error: no BLAS/LAPACK library loaded!
([NaN; NaN; … ; NaN; NaN;;], [6.9149587937626e-310], [NaN; NaN; … ; NaN; NaN;;], [0.0], 11, 15)
```
For information, PROPACK was compiled this [build_tarballs.jl](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/PROPACK/build_tarballs.jl).

cc @staticfloat

**Comment by staticfloat** [comment]
```
Processed 4945 symbols; forwarded 157 symbols with 64-bit interface and mangling to a suffix of "64_"
```

It looked for 4945 symbols, it only found 157.  Sounds like the BLAS library is quite incomplete, or it's finding the wrong symbol suffix.  If `libblis.so` only provides a subset of the symbols that are needed, you can load it with `clear=false` so that the symbols that `libblis.so` does not provide are provided instead by OpenBLAS.

If you want to figure out where the missing function call is coming from, do this:
```
function debug_missing_function()
    println("Missing BLAS/LAPACK function!")
    display(stacktrace())
end
LinearAlgebra.BLAS.lbt_set_default_func(@cfunction(debug_missing_function, Cvoid, ()))
```

**Comment by amontoison** [comment]
For MKL, I checked with `nm -D $(MKL_jll.libmkl_rt_path)` that the symbols required by PROPACK are in the library.

**Comment by amontoison** [comment]
I confirm that both MKL and BLIS have the BLAS symbols for PROPACK.

**Comment by staticfloat** [comment]
It's not just that PROPACK is satisfied; any Julia code that is run that uses BLAS symbols needs to be satisfied as well.

**Comment by ViralBShah** [comment]
Tried with AppleAccelerate and getting same error.

**Comment by ViralBShah** [comment]
PROPACK looks pretty straightforward - just links directly to LAPACK and BLAS. The build script looks right as well, so I am only guessing that we probably are missing some BLAS or LAPACK functions in the name mangling.

**Comment by ViralBShah** [comment]
One thing to do is to make sure that all the LAPACK symbols are compiled in are private to this library so that there is no risk they get replaced by forwarded versions, perhaps using the `all_load` / `noall_load` linking mechanism that is used in some Yggdrasil recipes (e.g. Coin-OR/CSDP).

**Comment by RalphAS** [comment]
This may be fixed by https://github.com/JuliaLinearAlgebra/MKL.jl/pull/140

**Comment by ViralBShah** [comment]
BTW, this did not get fixed by the PR.

**Comment by ViralBShah** [comment]
Works now with Julia 1.10.4 and LBT 5.9:

```
julia> using MKL

julia> using PROPACK

julia> tsvd(rand(20, 20))
([-0.2060419796110353; -0.2454011505143323; … ; -0.19251920965130948; -0.20989604037851442;;], [10.448019745507464], [-0.2316205727195162; -0.222697646579334; … ; -0.15296995156527565; -0.20513227779552395;;], [4.878769996642799e-38], 11, 11)
```
