### ISSUE TITLE
Move repo to JuliaLinearAlgebra

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/libblastrampoline#39]
Now that this is shipping with Julia, this repo should perhaps live in JuliaLang.

**Comment by giordano** [comment]
Or [/JuliaLinearAlgebra](https://github.com/JuliaLinearAlgebra)?

**Comment by ViralBShah** [comment]
Yeah, that would be fine too.

**Comment by ViralBShah** [comment]
Bump on this.

**Comment by ViralBShah** [comment]
Bump. @staticfloat Could you move this to `JuliaLinearAlgebra`?

**Comment by DilumAluthge** [comment]
This is done now.
