### ISSUE TITLE
Using different BLAS+LAPACK for Julia versions before and after 1.7 

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLinearAlgebra/libblastrampoline#65]
I implemented some LAPACK wrappers for the needs in [MatrixEquations](https://github.com/andreasvarga/MatrixEquations.jl) and [MatrixPencils](https://github.com/andreasvarga/MatrixPencils.jl). Recently I changed the setting of library from 

`const liblapack = Base.liblapack_name`

to

`const liblapack = VERSION < v"1.7" ? Base.liblapack_name : "libblastrampoline"`

I wonder however if this is the right way to do, because recently I encountered unexpected failures of [MatrixEquations](https://github.com/andreasvarga/MatrixEquations.jl) on the nightly runs, which I am trying to fix (one idea is just the possibly wrong setting of dependence of BLAS+LAPACK).

**Comment by jishnub** [comment]
Is this the recommended usage?

**Comment by andreasvarga** [comment]
I got no answer to my question, but this is the way I am using the packages to keep compatibility with Julia 1,6 (LTS).
