### ISSUE TITLE
FlexiBLAS

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLinearAlgebra/libblastrampoline#69]
I tried to use [FlexiBLAS](https://www.mpi-magdeburg.mpg.de/projects/flexiblas) as a BLAS/LAPACK backend for LBT. While `lbt_forward` seems to work (What does `2191` mean?) using it doesn't:

```julia
julia> libflexiblas = "/opt/software/pc2/EB-SW/software/FlexiBLAS/3.0.4-GCC-11.2.0/lib/libflexiblas.so"
"/opt/software/pc2/EB-SW/software/FlexiBLAS/3.0.4-GCC-11.2.0/lib/libflexiblas.so"

julia> using LinearAlgebra

julia> BLAS.lbt_forward(libflexiblas; clear=true)
2191

julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries:
└ [ LP64] libflexiblas.so

julia> A = rand(1000,1000);

julia> A*A;
Error: no BLAS/LAPACK library loaded!
```

Why doesn't this work given that FlexiBLAS claims to have 100% compatibility with BLAS/LAPACK ABI/API?

**Comment by giordano** [comment]
Doesn't flexiblas do basically the same work as libblastrampoline?

**Comment by carstenbauer** [comment]
Yes, it does. But we already have some infrastructure around flexiblas that we might want to reuse.

**Comment by staticfloat** [comment]
The issue here is that you've loaded an LP64 library, but Julia natively uses ILP64.  Try building FlexiBLAS in ILP64 mode, and loading it again.

**Comment by ViralBShah** [comment]
Let's reopen if still an issue after compiling FlexiBLAS with ILP64.
