### ISSUE TITLE
Get/Set number of threads of specific BLAS/LAPACK library (when there are multiple)

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLinearAlgebra/libblastrampoline#70]
IIUC, when there are multiple BLAS / LAPACK libraries stacked on top of each other, the `lbt_get_num_threads` / `lbt_set_num_threads` functions currently try to query or set the number of threads of all libraries. I wonder whether there should be a way (API) to get/set the number of threads of a particular library in the stack using the LBT-registered getter and setter functions, e.g. `lbt_get_num_threads(libindex)` and `lbt_set_num_threads(nthreads, libindex)`.

Triggered by [this](https://github.com/JuliaLinearAlgebra/BLIS.jl/issues/3#issuecomment-1106619678) discussion, where we stack BLIS (for BLAS) on top of OpenBLAS (for LAPACK). In this case, it might be useful to independently set the number of threads for BLIS and OpenBLAS (even more so in the future, where we might provide a LAPACK which uses the BLIS BLAS under the hood).

Thoughts?

**Comment by staticfloat** [comment]
I don't think this is something that LBT is going to do.  LBT is intended to make the calling code completely unaware of the underlying BLAS libraries, and as such, it's not intended to manage a suite of BLAS libraries.

If the calling application is cognizant of multiple loaded BLAS libraries... it should feel free to configure them itself!  Just call the thread set/get functions directly on the underlying BLAS libraries (you can even introspect to figure out which ones are loaded with the LBT config API if you want).
