### ISSUE TITLE
Update for OpenBLAS 0.3.20

### ISSUE THREAD

**Issue by jirutka** [JuliaLinearAlgebra/libblastrampoline#73]
According to [openblas_config.h](https://github.com/JuliaLinearAlgebra/libblastrampoline/blob/main/include/ILP64/x86_64-linux-musl/openblas_config.h), the currently supported OpenBLAS version is 0.3.13 from December 2020. Can you please update it for the latest version 0.3.20?

**Comment by giordano** [comment]
For the record, in Julia `master` we're currently using libblastrampoline with OpenBLAS 0.3.20 (and BLAS is tested pretty extensively). BLAS API is rather stable, the base version of OpenBLAS shouldn't matter too much, I think.

**Comment by staticfloat** [comment]
Yes, the BLAS API is pretty stable; unless they've added a new BLAS or LAPACK "verb", it shouldn't be necessary to update.
