### ISSUE TITLE
32-bit Windows CI is broken

### ISSUE THREAD

**Issue by ararslan** [JuliaLinearAlgebra/libblastrampoline#86]
All GitHub Actions builds for Windows x86 since July 2022 have failed, and the first one to fail was associated with the merge commit for #80, which literally only touched the README. All other platforms seem just fine.

**Comment by ViralBShah** [comment]
Seems like it is trying to do ILP64 on an x86 box. Maybe something changed in the way github provides these CI machines?

**Comment by staticfloat** [comment]
I've switched to buildkite, which is working.
