### ISSUE TITLE
Some problems with library on Windows

### ISSUE THREAD

**Issue by giordano** [JuliaLinearAlgebra/libblastrampoline#87]
There are currently two orthogonal issues with the library on Windows (spotted in https://github.com/jump-dev/Ipopt.jl/pull/327#issuecomment-1233458190):

* the soversion of the library, fixed in `src/Make.inc` is stalling: https://github.com/JuliaLinearAlgebra/libblastrampoline/blob/b829b0e1583da58bc80acbcc0cfb83b482530b92/src/Make.inc#L26-L28 but the latest release at the moment is v5.1.1
* https://github.com/JuliaLinearAlgebra/libblastrampoline/blob/b829b0e1583da58bc80acbcc0cfb83b482530b92/src/Makefile#L45-L46 generates the import library for `$@`, which is `LIB_FULL_VERSION`, which is a bad idea because it means the ABI is broken in every single version (well, every single version where the soversion is actually bumped, see point above)

An overall solution is probably to stop generating the library with the full name on Windows, or at least generating the import library for `LIB_MAJOR_VERSION` instead of `LIB_FULL_VERSION`.

It remains the problem of actually remembering to update the soversion in `src/Make.inc` when doing a new release.

CC: @ViralBShah

**Comment by giordano** [comment]
> So should we sync the version, or just have only the major version?

In any case we should generate the import library for `LIB_MAJOR_VERSION`, not for `LIB_FULL_VERSION`, that's a really bad idea.  There is the question of whether to keep `LIB_FULL_VERSION` around.

Going forward it'd be great the have the soversion actually match the "version number" of the package, otherwise it's an inconsistent mess.

> I assume we need Julia 1.8.1 with this fix, right?

Yes, but fixing this issue will break the ABI of the library on Windows.

**Comment by ViralBShah** [comment]
Will this fix the null pointer issue in mumps_seq and ipopt_jll on windows? Is it still something else?

**Comment by giordano** [comment]
I don't think this is the culprit there, but it is a compatibility problem

**Comment by giordano** [comment]
> Will this fix the null pointer issue in mumps_seq and ipopt_jll on windows? Is it still something else?

For the record, that issue is tracked by #89, and may be related to the confusion between the libraries available on Windows.
